address: :9090
frontendOrigins:
    - http://localhost:8181
routes:
    multipleFiles:
        servepath: /multiple
        savepath: ./static/multipleFiles
        fullpath: http://localhost:9090/static/multipleFiles
        fileserve: /static/multipleFiles
        multiple: true
        rename: true
    files:
        servepath: /notmultiple
        savepath: ./static/files
        fullpath: http://localhost:9090/static/files
        fileserve: /static/files
        multiple: false
        rename: true
